# config file
version:2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from github
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            py -m venv venv
            .\venv\bin\activate
            py -m pip install -r requirements.txt
      # .\calculatorApp\Scripts\activate
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            .\venv\bin\activate
            py -m flake8 --exclude=venv* --statistics
            py -m pytest -v --cov=calculator
